name: Autocancel redundant workflow
on:
  push:
    branches:
      - 'master'
    paths:
      - 'resources/go/*'    
      - '.github/workflows/autocancel-workflow.yml'    

jobs:
  autocancel_build_no_condition:
    name: Autocancel workflow (no condition)
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build Project
        run: |
          cd resources/go
          GOOS=linux GOARCH=amd64 go build -o dist/hello .
          zip --junk-paths -r go-project-artifact dist

  autocancel_build_with_condition:
    name: Autocancel workflow (Conditional)
    runs-on: ubuntu-latest
    steps:
      ## Only run this action when it's NOT on tags or master
      - uses: rokroskar/workflow-run-cleanup-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build Project
        run: |
          cd resources/go
          GOOS=linux GOARCH=amd64 go build -o dist/hello .
          zip --junk-paths -r go-project-artifact dist
